spring:
  cloud:
    stream:
      function:
        definition: enricher
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        inputTable:
          destination: user_data
          content-type: application/json
          group: customaggregator-group
          value.serde: com.ballaci.kstreams.serdesCustomSerdes$UserDataSerde
        inputStream:
          destination: orders
          content-type: application/json
          group: customaggregator-group
          value.serde: com.ballaci.kstreams.serdesCustomSerdes$OrderThinSerde
        outputStream:
          destination: orders_enriched
          content-type: application/json
          value.serde: com.ballaci.kstreams.serdesCustomSerdes$OrderFullSerde
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            functions.enricher.groupId: enricher-group
#debug: true

logging:
  level:
    ROOT: ERROR
    org.apache.kafka: ERROR
    com.ballaci: TRACE