spring:
  cloud:
    stream:
      function:
        definition: route
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        userTags:
          destination: user_tags
          content-type: application/json
          group: tags-group
          value.serde: com.ballaci.kstreams.serdesCustomSerdes$UserTagsSerde
        documents:
          destination: documents
          content-type: application/json
          group: documents-group
          value.serde: com.ballaci.kstreams.serdesCustomSerdes$DocumentSerde
        documentApproval:
          destination: document_approval
          content-type: application/json
          value.serde: com.ballaci.kstreams.serdesCustomSerdes$DocumentSerde
        notRelevant:
          destination: not_relevant
          content-type: application/json
          value.serde: com.ballaci.kstreams.serdesCustomSerdes$DocumentSerde
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            functions.route.groupId: router-group
#debug: true

logging:
  level:
    ROOT: ERROR
    org.apache.kafka: ERROR
    com.ballaci: TRACE